### ISSUE TITLE
ultraplugin/module-paymentfee disappeared

### ISSUE THREAD

**Issue by p24-max** [ultraplugin/module-base#1]
Hi,
the repository ultraplugin/module-paymentfee suddenly disappeared, can you please recover it? Just deleting it breaks ci/cd builds.
Thank you!

**Comment by ultraplugin** [comment]
Hi @p24-max We have removed the extension from our repository due to copyrights. Please remove this extension from your project and add original extension.

Extension: https://github.com/mageprince/magento2-paymentfee
Packagist: https://packagist.org/packages/mageprince/magento2-paymentfee
Composer: `composer require mageprince/magento2-paymentfee`
